### ISSUE TITLE
Distribute page should not break if location API is not available

### ISSUE THREAD

**Issue by brooklynbagel** [leveler-dba/leveler#124]
As per the discussion brought up by @codebling  in PR #123.

I think the fall back if there API is unavailable should be to not filter based off location and just display entries from anywhere.

Any thoughts?

@samyoungnyc including you in the discussion if you've got any thoughts or I'm missing somebody

**Comment by codebling** [comment]
Perfect, was just creating an issue. 

If the request to `ipdata.co` fails, we don't retrieve the list of entries. This means that the Distribute is unuseable if: 

1) IPData is down, 
2) the user has an IP address which makes IPData choke, 
3) we exceed the IPData API limit

Since the "default" (aka non-US) handling does not rely on geolocation data, we can just use that. It simply takes 10 random entries from the DB, which is better than nothing. 



[original comment](https://github.com/leveler-dba/leveler/pull/123#issuecomment-624936058)
